# #workflow
# title: Website name
# description: A website for uplaoding content
# age: 30
# tags:
#  - technology
#  - images
#  - creative
# address:
#   street: mg road
#   city: pune
#   state: na
# value: ${{env.VALUE}}
# variable: ${{github.VARIABLE_NAME}}

name: github action ofr
on:
  push:
      branches: [main]
jobs:
  build:
     runs-on: windows
     steps:
          -uses: actions/checkout@v2
          -name: Print hello world
          -run: echo "Hello world"

